services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: treka_frontend
    ports:
      - "3001:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    restart: unless-stopped
